---
title: "Data Wrangling final"
author: "Kwadwo Amoako"
date: "November 20, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
setting up the channel to connect R to database

```{r}
library(RODBC)
mycom <- odbcConnect("dartmouth1","kamoako","Kamoako@qbs181")
```
Impoting Demographics,Textmessages and chronicconditions

```{r}
demographics <- sqlQuery(mycom, "select * from Demographics")
textmessages <- sqlQuery(mycom,"select * from Text")
chronicconditions <- sqlQuery(mycom, "select * from ChronicConditions")
```

merging  the 3 tables into one big tables imported into R
```{r ,warning=FALSE}
library(dplyr)
mrg1 <- demographics %>% inner_join(chronicconditions, by = c('contactid' = 'tri_patientid'))
 mrg2 <-  mrg1 %>% inner_join(textmessages, by = c('contactid'='tri_contactId'))
#create table with unique ids based on last text sent date
finalmerge <- mrg2 %>%
group_by(contactid) %>% top_n(1, TextSentDate)
#dropping some unwanted columns
finalmerge$test <- NULL
finalmerge$gh1 <- NULL
finalmerge$gh2 <- NULL
finalmerge$pf02 <- NULL
finalmerge$gh3 <- NULL
finalmerge$gh4 <- NULL
finalmerge$gh5 <- NULL
```


